[platformio]
default_envs = t-beam-sx1262

[env]
monitor_speed = 115200
upload_speed = 921600
build_src_filter =
    -<*>
; Dependencies
[esp32_base]
platform = espressif32@6.12.0
framework = arduino
lib_deps =
; uncomment the following line to use the build in main branch, which pulls all dependencies
    symlink://./
build_flags =
    -D CDP_LOG_INFO
    -D SOC_I2C_SUPPORTED
    -std=gnu++2a

[env:t-beam-sx1262]
extends = esp32_base
board = ttgo-t-beam
build_src_filter =
    +<examples/BasicDuckFirmware/src/*.cpp>
lib_deps =
    ${esp32_base.lib_deps}
    olikraus/U8g2@^2.36.17
build_flags =
    ${esp32_base.build_flags}
    -D ARDUINO_T_BEAM

build_unflags =
    -std=gnu++11

[env:t-beam-sx1276]
extends = esp32_base
board = ttgo-lora32-v1
build_src_filter =
    +<examples/BasicDuckFirmware/src/*.cpp>
lib_deps =
    ${esp32_base.lib_deps}
build_flags =
    ${esp32_base.build_flags}
    -DXPOWERS_CHIP_AXP192
build_unflags =
    -std=gnu++11