; PlatformIO Project Configuration File
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = Duck Display Quack-Pack
default_envs = prod_heltec_wifi_lora_32_V3

[env]
monitor_speed = 115200
upload_speed = 921600
build_src_filter =
	-<*>

[esp32_base]
monitor_speed = 115200
monitor_filters = time
lib_compat_mode = strict
lib_ldf_mode = chain
build_flags =
	-std=gnu++2a
	-Wno-inconsistent-missing-override
	-Wno-missing-field-initializers
	-Wno-format
	-D CDP_LOG_INFO
;	-I ./src
build_unflags = 
	-std=gnu++11
platform = espressif32@6.12.0
board = esp32dev
framework = arduino

[dev_cdp]
extends = esp32_base
lib_deps =
	symlink://./
	https://github.com/Project-Owl/QuackPack-Base
build_src_filter =
	${env.build_src_filter}
build_flags =
	${esp32_base.build_flags}
	-DCDP_LOG_DEBUG

[env:tbeam-sx1262-u8g2]
extends = dev_cdp
board = ttgo-t-beam
build_src_filter =
	${dev_cdp.build_src_filter}
	+<../examples/MamaDuck/U8G2/*.cpp>
	+<../examples/MamaDuck/U8G2/*.h>
lib_deps =
	${dev_cdp.lib_deps}
build_flags =
	${dev_cdp.build_flags}
	-DXPOWERS_CHIP_AXP192
build_unflags =
	-std=gnu++11

[env:tbeam-sx1262-adafruit]
extends = dev_cdp
board = ttgo-t-beam
build_src_filter =
	${dev_cdp.build_src_filter}
	+<../examples/MamaDuck/adafruit/*.cpp>
	+<../examples/MamaDuck/adafruit/*.h>
lib_deps =
	${dev_cdp.lib_deps}
build_flags =
	${dev_cdp.build_flags}
	-DXPOWERS_CHIP_AXP192
build_unflags =
	-std=gnu++11

[env:release_cdp]
extends = esp32_base
lib_deps =
	https://github.com/ClusterDuck-Protocol/ClusterDuck-Protocol/archive/refs/tags/5.0.0.zip
	https://github.com/Project-Owl/QuackPack-Base
	adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
	adafruit/Adafruit BusIO
[env:prod_heltec_wifi_lora_32_V2]
extends = env:release_cdp
board = heltec_wifi_lora_32_V2

[env:prod_heltec_wifi_lora_32_V3]
extends = env:release_cdp
board = heltec_wifi_lora_32_V3

[env:prod_lilygo_t_beam_sx1262]
extends = env:release_cdp
board = ttgo-t-beam

[env:prod_lilygo_t_beam_supreme_sx1262]
extends = env:release_cdp
board = esp32-s3-devkitc-1
build_flags = 
	${env:release_cdp.build_flags}
	-DARDUINO_LILYGO_T_BEAM_SUPREME
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
upload_speed = 921600
monitor_speed = 115200

[env:prod_lilygo_t_beam_sx1276]
extends = env:release_cdp
board = ttgo-lora32-v1

[env:prod_ttgo_lora32_v1_3]
extends = env:release_cdp
board = ttgo-lora32-v1
build_flags = 
	${env:esp32_base.build_flags}
	-DTTGO_1_3
